plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
author: Kulpreet Singh
theme: minima
twitter_username: jungly
github_username: pool2win
description: Bitcoin, distributed systems and Rust
header_pages:
  - specification.md
show_excerpts: true
title: Development blog for jungly/pool2win
logo: assets/BC_Logo_.png
twitter:
  card: summary
  username: jungly
