plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: pool2win
    github: pool2win
show_excerpts: true
title: Braidpool Development Blog
tagline: Dev progress
description: Braidpool development, progress and other plans
logo: assets/epoch.png
twitter:
  card: summary
  username: pool2win
