plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/pool2win" }
    - { platform: twitter, user_url: "https://twitter.com/pool2win" }
header_pages:
  - specification.md
show_excerpts: true
title: Braidpool Development Blog
tagline: Dev progress
description: Braidpool development, progress and other plans
logo: assets/BC_Logo_.png
twitter:
  card: summary
  username: pool2win
