plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: pool2win
    github: pool2win
show_excerpts: true
site:
  title: Braidpool Dev Blog
  tagline: Braidpool development
  description: Braidpool development, progress and other plans
