plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
author: ""
theme: minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/pool2win" }
    - { platform: twitter, user_url: "https://twitter.com/jungly" }
header_pages:
  - specification.md
show_excerpts: true
title: Development blog for jungly/pool2win
logo: assets/BC_Logo_.png
twitter:
  card: summary
  username: jungly
